# Generated by Django 3.0.8 on 2020-07-29 13:05

from django.db import migrations, models
import inventory.utils


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to=inventory.utils.uuid_upload_to),
        ),
    ]
